### PR TITLE
add XZ1 and XZ2 fingerprint

### PR DESCRIPTION
**Pull request by alviteri**
picked from stock system dump

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by Didgeridoohan** [comment]
Have you tested the XZ2 prints? They're all dev-keys, and that usually means that they don't pass the ctsProfile.

I'll test myself when I get a chance, but just in case you already have.

**Comment by alviteri** [comment]
I have XZ2 dual and XZ2 compact on stock firmware with locked bootloader and both say the same unfortunately they haven't tested in magisk yet XZ1 was successfully tested

**Comment by Didgeridoohan** [comment]
Neither of the XZ2 fingerprints pass on my test device. I'll add the XZ1 when I get a chance though.

**Comment by alviteri** [comment]
ro.build.fingerprint should be right ... Also ro.vendor.build.fingerprint are the same ... .mmm ok

**Comment by alviteri** [comment]
updated with xz1 fingerprint only

**Comment by alviteri** [comment]
added correct xz2 fingerprints

**Comment by alviteri** [comment]
added xa2 family fingerprints

**Comment by alviteri** [comment]
added XZ Premium variants too

**Comment by alviteri** [comment]
added some other devices single and dual sim

**Comment by alviteri** [comment]
screenshot_20180720-213458
screenshot_20180720-213440

**Comment by oshmoun** [comment]
kugo doesn't pass cts using its fingerprint.
suzu's fingerprint works find on kugo though

**Comment by alviteri** [comment]
screenshot_20180721-063541
screenshot_20180721-063523
@oshmoun

**Comment by Didgeridoohan** [comment]
I've added the working fingerprints to the list (the XA2 and XZs prints wouldn't pass on my test device).

Thank you again!

**Pull request closed without merging**
